apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8s-demo
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: 745815529977.dkr.ecr.us-east-2.amazonaws.com/dmarc-digests
    argocd-image-updater.argoproj.io/dmarc-digests.update-strategy: digest
spec:
  destination:
    namespace: k8s-demo
    server: https://kubernetes.default.svc
  project: default
  source:
    path: k8s
    repoURL: https://github.com/rmgpinto/k8s-argocd-demo.git
    targetRevision: dd
    helm:
      valueFiles:
        - values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
