apiVersion: v1
kind: Service
metadata:
  name: app-a
  namespace: default
  labels:
    app: app-a
spec:
  selector:
    app: app-a
  ports:
    - name: http
      protocol: TCP
      appProtocol: http
      port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: app-a-stable
  namespace: default
spec:
  selector:
    app: app-a
  ports:
    - protocol: TCP
      appProtocol: http
      port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: app-a-canary
  namespace: default
spec:
  selector:
    app: app-a
  ports:
    - protocol: TCP
      appProtocol: http
      port: 8080
      targetPort: 8080
