apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: app-b
  namespace: default
spec:
  replicas: 5
  selector:
    matchLabels:
      app: app-b
  template:
    metadata:
      labels:
        app: app-b
    spec:
      containers:
        - name: app-b
          image: 930237623491.dkr.ecr.us-east-2.amazonaws.com/app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: HTTP_CODE
              value: "200"
  strategy:
    canary:
      stableService: app-b-stable
      canaryService: app-b-canary
      stableMetadata:
        labels:
          role: stable
          # kuma.io/gateway: enabled
          # kuma.io/sidecar-injection: enabled
      canaryMetadata:
        labels:
          role: canary
          # kuma.io/gateway: enabled
          # kuma.io/sidecar-injection: enabled
      # analysis:
      #   templates:
      #     - templateName: app-b-bnalysis
      steps:
        - setWeight: 20 # 1 pod canary / 4 pods stable
        - pause: { duration: 2m }
        - setWeight: 40 # 2 pods canary / 3 pods stable
        - pause: { duration: 30s }
        - setWeight: 60 # 3 pods canary / 2 pods stable
        - pause: { duration: 30s }
