apiVersion: v1
kind: Service
metadata:
  name: app-b
  namespace: default
  labels:
    app: app-b
spec:
  selector:
    app: app-b
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: app-b-stable
  namespace: default
spec:
  selector:
    app: app-b
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: app-b-canary
  namespace: default
spec:
  selector:
    app: app-b
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
