apiVersion: apps/v1
kind: Deployment
metadata:
  name: dmarc-digests
  namespace: default
  labels:
    app: dmarc-digests
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dmarc-digests
  template:
    metadata:
      labels:
        app: dmarc-digests
    spec:
      containers:
        - name: dmarc-digests
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          command:
            - /bin/sh
            - -c
            - |
              sleep 999
      nodeSelector:
        kubernetes.io/arch: amd64