apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: main
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: main
  template:
    metadata:
      labels:
        app: main
    spec:
      containers:
        - name: main
          image: 930237623491.dkr.ecr.us-east-2.amazonaws.com/main:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: MICROSERVICE_A
              value: http://app-a.default:8080
            - name: MICROSERVICE_B
              value: http://app-b.default:8080
  strategy:
    canary:
      stableService: main-stable
      canaryService: main-canary
      stableMetadata:
        labels:
          role: stable
          {{ if .Values.mesh -}}
          kuma.io/gateway: enabled
          kuma.io/sidecar-injection: enabled
          {{ end -}}
      canaryMetadata:
        labels:
          role: canary
          {{ if .Values.mesh -}}
          kuma.io/gateway: enabled
          kuma.io/sidecar-injection: enabled
          {{- end }}
      steps:
        - setWeight: 20
        - pause: { duration: 2m }
        - setWeight: 40
        - pause: { duration: 30s }
        - setWeight: 60
        - pause: { duration: 30s }
