apiVersion: v1
kind: Service
metadata:
  name: main
  namespace: default
  labels:
    app: main
spec:
  selector:
    app: main
  ports:
    - name: http
      protocol: TCP
      appProtocol: http
      port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: main-stable
  namespace: default
spec:
  selector:
    app: main
  ports:
    - protocol: TCP
      appProtocol: http
      port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: main-canary
  namespace: default
spec:
  selector:
    app: main
  ports:
    - protocol: TCP
      appProtocol: http
      port: 8080
      targetPort: 8080
