apiVersion: apps/v1
kind: Deployment
metadata:
  name: probe
  namespace: default
  labels:
    app: probe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: probe
  template:
    metadata:
      labels:
        app: probe
        {{- if .Values.gateway }}
        kuma.io/gateway: enabled
        {{- end }}
        {{- if .Values.mesh }}
        kuma.io/sidecar-injection: enabled
        {{- end }}
    spec:
      containers:
        - name: probe
          image: alpine:latest
          command:
            - /bin/sh
            - -c
            - |
              apk add curl
              while [ "1" = "1" ]; do
                sleep 1
                echo $(date) $(curl -s http://main.default:8080)
              done
          env:
            - name: MAIN_ADDR
            {{- if .Values.mesh }}
              value: main_default_svc_8080.mesh:80
            {{- else }}
              value: http://main.default:8080
            {{- else }}
          resources:
            limits:
              cpu: 1000m
              memory: 1Gi
