apiVersion: apps/v1
kind: Deployment
metadata:
  name: probe
  namespace: default
  labels:
    app: probe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: probe
  template:
    metadata:
      labels:
        app: probe
    spec:
      containers:
        - name: probe
          image: curlimages/curl:latest
          command:
            - /bin/sh
            - -c
            - |
              while [ "1" = "1" ]; do
                sleep 1
                echo $(date) $(curl -s $MAIN_ADDR)
              done
          env:
            - name: MAIN_ADDR
            {{- if .Values.mesh }}
              value: http://main_default_svc_8080.mesh:80
            {{- else }}
              value: http://main.default:8080
            {{- end }}
          resources:
            limits:
              cpu: 1000m
              memory: 1Gi
